version: '3.8'

services:

  app:
    build: .
    container_name: node-newapp
    restart: always
    ports: 
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=ep-black-breeze-a22ojwv3-pooler.eu-central-1.aws.neon.tech
      - DB_USER=neondb_owner
      - DB_PASSWORD=npg_q7ZYsQBVpAo8
      - DB_NAME=neondb